### ISSUE TITLE
Add new cheatsheet

### ISSUE THREAD

**Issue by stevenpersia** [stevenpersia/ultimate-cheatsheet#1]
Feel free to add some cheatsheet 👍 

Accepted cheatsheet : 
- CSS
- Javascript
- React
- Typescript

**Comment by wajeehsheikh** [comment]
Hi,
I would like to add some JavaScript and React cheatsheets. I will create the condition cheatsheet for JavaScript. 

Thank you,
Waj

**Comment by silltho** [comment]
Hey,
I would love to create a typescript interfaces cheatsheet.

**Comment by stevenpersia** [comment]
Thank you @wajeehsheikh and @silltho !
